"""fds

Revision ID: 6cf44276ddca
Revises: 
Create Date: 2021-07-22 20:25:07.589496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf44276ddca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_on', sa.Date(), nullable=True),
    sa.Column('book_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_on_id', sa.Integer(), nullable=True),
    sa.Column('book_from', sa.Integer(), nullable=True),
    sa.Column('book_to', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_on_id'], ['booking_date.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_time')
    op.drop_table('booking_date')
    # ### end Alembic commands ###
