"""heroku

Revision ID: ac4d9c938c5b
Revises: 
Create Date: 2021-08-04 10:20:00.144683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac4d9c938c5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_on', sa.Date(), nullable=True),
    sa.Column('book_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_on_id', sa.Integer(), nullable=True),
    sa.Column('book_from', sa.Integer(), nullable=True),
    sa.Column('book_to', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_on_id'], ['booking_date.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_time')
    op.drop_table('booking_date')
    # ### end Alembic commands ###
